### ISSUE TITLE
Read Only FTP

### ISSUE THREAD

**Issue by jomir199** [Guichaguri/MinimalFTP#11]
Hi, I would like to implement a read only FTP server. How to do this? Do I need to disable some default command or other things?

Thank you.

**Comment by Guichaguri** [comment]
Hello, sorry for the late response

You just need to extend [NativeFileSystem](https://github.com/Guichaguri/MinimalFTP/blob/master/src/main/java/com/guichaguri/minimalftp/impl/NativeFileSystem.java) and override write methods such as `writeFile`, `mkdirs`, `delete`, `rename`, `touch` and `chmod` to make them always throw exceptions. All write commands will be rejected.

Then you can create a custom authenticator that will return that NativeFileSystem instance.
