### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown pattern character 'Y'

### ISSUE THREAD

**Issue by kyze8439690** [Guichaguri/MinimalFTP#14]
Crash log:
```
Caused by java.lang.IllegalArgumentException: Unknown pattern character 'Y'
       at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:314)
       at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:289)
       at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:356)
       at com.guichaguri.minimalftp.Utils.<clinit>(Utils.java:49)
       at com.guichaguri.minimalftp.FTPServer.listen(FTPServer.java:201)
```

Problem line:
https://github.com/Guichaguri/MinimalFTP/blob/3afd39c48da224eabb634fa060827e42a8a803a1/src/main/java/com/guichaguri/minimalftp/Utils.java#L49
https://github.com/Guichaguri/MinimalFTP/blob/3afd39c48da224eabb634fa060827e42a8a803a1/src/main/java/com/guichaguri/minimalftp/Utils.java#L52

Crash platform: 
- Android 5
- Android 5.1
- Android 6

According to [Java SimpleDateFormat document](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html), **Year** can be represented by lower case 'y', Upper case 'Y' represent **Week year**, which is not supported in lower version of Android. Maybe you can change to lower case y to improve compatibility on Android platform?

**Comment by Guichaguri** [comment]
Thanks for reporting this issue! Of all the things this project does, I've never thought the date format would be the issue on Android

Could you create a pull request fixing this issue?
