### ISSUE TITLE
Passive mode port range configuration

### ISSUE THREAD

**Issue by fatihpense** [Guichaguri/MinimalFTP#4]
Hello thanks for the nice library. 
Is there a way to specify passive port range?

Regards, Fatih

**Comment by Guichaguri** [comment]
This can't be implemented at the moment. I initialize passive servers using the port `0`, [as documented](https://docs.oracle.com/javase/8/docs/api/java/net/ServerSocket.html#ServerSocket-int-):
> A port number of 0 means that the port number is automatically allocated, typically from an ephemeral port range.

Unless you control port allocations manually, there's no other way to implement a port range.

**Comment by fatihpense** [comment]
I see Guichaguri, thank you for the response. You can close the issue if you want.
Regards, Fatih
