### ISSUE TITLE
Multithread requirements of IFileSystem.java implementations

### ISSUE THREAD

**Issue by proofrock** [Guichaguri/MinimalFTP#6]
Hi,
  the class that implements IFileSystem must be thread safe, right? Are there methods that are called by one thread only? Is there a way to make everything "one thread only"?

Also, is it possible that two clients write on the same file, at the same time, so that the two OutputStream(s)  must be "coordinated" (i.e., the second call to write() doesn't return until the close() method on the first OutputStream is called)? It's important for me to know this because the implementation is quite difficult, as it must take into account what happens when close() is not called because the client crashes.

I'm developing a project in which FTP is not backed by a filesystem, and so I can't use the out-of-the-box locking primitives of the "real" filesystem as you seem to do in the "reference" implementation.

Cheers, and thanks, and you did an excellent (excellent!) work,

--Germano

**Comment by Guichaguri** [comment]
Basically, the server depends on the authenticator to create file systems. In the [NoOpAuthenticator](https://github.com/Guichaguri/MinimalFTP/blob/master/src/main/java/com/guichaguri/minimalftp/impl/NoOpAuthenticator.java#L55), it uses the same file system instance throughout the whole server, but in [this example](https://github.com/Guichaguri/MinimalFTP/blob/master/src/test/java/com/guichaguri/minimalftp/custom/UserbaseAuthenticator.java#L65), it creates one file system for each connection.

Each connection uses the same thread for every operation. If you need the file system to not use concurrent threads throughout all connections, you should be able to implement a `synchronized` block inside each method with a static lock.

```java
public static Object fsLock = new Object();

@Override
public void delete(File file) throws IOException {
    synchronized(fsLock) {
        // ...
    }
}

@Override
public void mkdirs(File file) throws IOException {
    synchronized(fsLock) {
        // ...
    }
}

// ...
```

Yes, it is possible for two clients to write into the same file. Again, you could use locks to prevent that, but I think there are better (and faster) ways to do that.

This server is very basic, when it receives a command, it immediately calls the respective method. No locks or synchronization is done, you have to implement it manually.

**Comment by proofrock** [comment]
Ok. I use the same IFileSystem instance for all the connections, so it must be thread safe; and I'm also lock()ing the file accesses. Thanks for the explanation.
