### ISSUE TITLE
IFileSystem: when delete() is called on a dir, should I delete its contents as well?

### ISSUE THREAD

**Issue by proofrock** [Guichaguri/MinimalFTP#7]
Hi,
   when delete() is called on a directory, is it called also recursively on its contents? In Filezilla it seems so, but I don't know if it's true in general. 

I know that in a filesystem, deleting a directory deletes its contents, but I need to release resources for files.

Thanks again,

--Germano

PS: I don't use links, neither hard nor symbolic

**Comment by Guichaguri** [comment]
According to the [RFC 959](https://tools.ietf.org/html/rfc959), the client must send a `DELE` command to delete a file and a `RMD` command to delete a directory. In MinimalFTP, both commands call the `delete` method in the file system object. So yes, `delete` should remove directories too.

**Comment by proofrock** [comment]
Thanks. The question was more about: should I expect an empty directory (because files are deleted recursively before it by FTP) or not? Anyway, I'm deleting recursively myself, to be on the safe side.

**Comment by Guichaguri** [comment]
No, according to the spec, the client only sends a single `RMD` command. It should be your job to remove all files recursively.

**Comment by proofrock** [comment]
Thanks!
