### ISSUE TITLE
Server on Linux not working when accessing from Filezilla on Windows

### ISSUE THREAD

**Issue by proofrock** [Guichaguri/MinimalFTP#8]
Hi,
    I'm testing MinimalFTP under Linux (x86-64, Arch Linux, JVM 10.0.2) and it doesn't seem to work when accessing it from Filezilla. I thought it was my app, but the minimal code example in your README doesn't work either.

Please note that:

- it doesn't work with Filezilla (remote), but the standard linux "ftp" commandline client (localhost) works fine
- running the server under windows and accessing it with Filezilla (locahost) works
- running the server under windows and accessing it with the linux "ftp" util (remote) works, as well
- either server works accessing it from Firefox (both remote and localhost; read only, of course)
- it doesn't seems to be the case that "localhost works, and everything else don't" (also: no firewall, local LAN)
- no errors on the console (is there a way to "step up" the logging level?)

This is the Filezilla log:

> Command:	PWD
Response:	257 "/" CWD Name
Command:	TYPE I
Response:	200 Type set to I
Command:	PASV
Response:	227 Enabled Passive Mode (127,0,0,1,146,245)
Command:	MLSD
Response:	150 Sending file information list...
Error:	Data connection can't be estabilished. ECONNREFUSED - Connection refused by the server

(I translated from italian, sorry for any imprecision).

Thanks,

--Germano

**Comment by Guichaguri** [comment]
The problem is probably firewall. You're using passive mode, which picks a random port to start a server.
Try setting FileZilla to use active mode instead.

**Comment by proofrock** [comment]
Hmmm... interesting. There was a firewall, and disabling it does the trick _in active mode_. In passive mode, same error message even when disabling the firewall (and also running the server as root). I'll use active mode for now, do you know how can I test passive mode ports?

**Comment by Guichaguri** [comment]
I use Java's automatic port allocation, which picks a random port from an [ephemeral range](https://en.wikipedia.org/wiki/Ephemeral_port).

I can add an option to disable passive mode in the server, so clients such as Filezilla will automatically pick active mode.

**Comment by proofrock** [comment]
Would be nice, but don't sweat on it. If you feel like doing it - thanks a lot. No pressure. :wink:
